#-------------------------------------------------------------------------------------
# site settings
#-------------------------------------------------------------------------------------
version: 1 # increment version to force a site rebuild and update Recent News even if content is unchanged
title: John Doe Laboratory # in top navigation bar (navbar) and <head>
description: John Doe Laboratory, University of Michigan Medical School # description in <head>
author: John Doe                    # for copyright statement in footer
url: "https://jdoe-umich.github.io" # no slash at the end
# baseurl: "/sitename"              # only required if your site is on a subdomain e.g. https://username.github.io/sitename
                                    # which has url: "https://username.github.io" (no slash) and baseurl: "/sitename" (leading slash)
#-------------------------------------------------------------------------------------
# social profile of the principal investigator; icon links shown in footer
#-------------------------------------------------------------------------------------
email: jdoe@umich.edu
twitter_username: null
github_username: jdoe-umich
#-------------------------------------------------------------------------------------
# theme display settings
#-------------------------------------------------------------------------------------
max_posts_newsfeed: 24  # Show x number of recent news posts on the dedicated Newsfeed page
max_posts_home: 3       # Show x number of recent news posts on home page
max_posts_other: 10     # Show x number of recent news posts on other pages
max_projects_home: 12   # Show x number of active projects on home page
max_words_card_short: 25  # truncate project, people and news descriptions after this many words in cards
max_words_card_long: 50   # truncate other descriptions after this many words in cards
logo: /assets/images/1280px-Michigan_Wolverines_logo-90px_height.png  # Logo in navbar, will be displayed at 30px height
colors:
  links:  "#2F65A7"    # Color for links: use a readable color that contrasts well with dark text


# !!! only developers should edit below this line !!!


#-------------------------------------------------------------------------------------
# collections of data pages; only developers should edit this section
#-------------------------------------------------------------------------------------
# collections folders carry markdown files with expanded views of some or all data items
# Newsfeed items use the hard-coded Jekyll _posts collection
#-------------------------------------------------------------------------------------
collections_dir: content
collections:
#-------------------------------------------------------------------------------------
  projects: # found in the _projects folder, etc.   
    name: projects
    item: project
    link: page_always
    output: true   
    hue: 225 # blue
  resources: 
    name: resources
    item: resource
    link: page_if_exists
    output: true 
    hue: 0 # red
  people: 
    name: people
    item: person
    link: hash_always
    output: true   
    hue: 45 # gold
  funding: 
    name: funding
    item: funding
    link: hash_always
    output: true   
    hue: 135 # green
  publications: 
    name: publications
    item: publication
    link: hash_always
    output: true   
    hue: 270 # purple
  newsfeed: 
    name: newsfeed
    item: post
    link: never
    output: true
    hue: 180 # cyan

# eight equally spaced color hues: 
# 0 red
# 45 gold
# 90 limegreen
# 135 green
# 180 cyan
# 225 blue
# 270 purple
# 315 magenta

#-------------------------------------------------------------------------------------
# frontmatter defaults; only developers should edit this section
#-------------------------------------------------------------------------------------
defaults:
  -
    scope:
      path: ""
      type: "projects"
    values:
      permalink: "/projects/:slug/"
      layout: "items/project"
  -
    scope:
      path: ""
      type: "people"
    values:
      permalink: "/people/:slug/"
      layout: "items/person"
  -
    scope:
      path: ""
      type: "publications"
    values:
      permalink: "/publications/:slug/"
      layout: "items/publication"
  -
    scope:
      path: ""
      type: "funding"
    values:
      permalink: "/funding/:slug/"
      layout: "items/funding"
  -
    scope:
      path: ""
      type: "resources"
    values:
      permalink: "/resources/:slug/"
      layout: "items/resource" 
  -
    scope:
      path: ""
      type: "newsfeed"
    values:
      permalink: "/newsfeed/:slug/"
      layout: "items/post"
  -
    scope:
      path: ""
    values:
      layout: "base/default" # Only required for Petridish website, implied for sites using a theme

#-------------------------------------------------------------------------------------
# build settings; only developers should edit this section
#-------------------------------------------------------------------------------------
remote_theme: wilsonte-umich/umich-labs
markdown: kramdown
plugins: # If you build your site on gh-pages, only use these plugins: https://pages.github.com/versions/
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - LICENSE
  - package-lock.json
  - package.json
  - petridish.gemspec

#-------------------------------------------------------------------------------------
# legacy color settings from petridish, not used by umich-labs
#-------------------------------------------------------------------------------------
banner: "pink"    # Background color for page banners: use color that contrasts well with white
footer: "pink"    # Background color for footer: use color that contrasts well with white
